RockPaperScissors/RockPaperScissors/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RockPaperScissors.Models
{
    public class Game
    {
        [Display(Name = "Pick your choice")]
        [Required]
        public string UsersGuess { get; set; }
        public string ComputersGuess { get; set; }
        public string Winner { get; set; }

        public List<string> Options
        {
            get
            {
                return new List<string> { "Rock", "Paper", "Scissors" };
            }
        }

        public void Play()
        {
            var random = new Random().Next(Options.Count);
            ComputersGuess = Options[random];
            Winner = GameLogic(UsersGuess, ComputersGuess);
        }

        public string GameLogic(string user, string computer)
        {
            if (((user == "Rock") && (computer == "Rock")) || ((user == "Paper") && (computer == "Paper")) || ((user == "Scissors") && (computer == "Scissors")))
            {
                return "Tied game";
            }

            if (((user == "Rock") && (computer != "Paper")) || ((user == "Paper") && (computer != "Scissors")) || ((user == "Scissors") && (computer != "Rock")))
            {
                return "You win!";
            }

            return "You Lose!";
        }
    }
}

RockPaperScissors/RockPaperScissors/Controllers/GameController.cs
using System.Web.Mvc;
using RockPaperScissors.Models;

namespace RockPaperScissors.Controllers
{
    public class GameController : Controller
    {
        public ActionResult Play()
        {
            var model = new Game();
            return View(model);
        }

        [HttpPost]
        public ActionResult Play(Game model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            return RedirectToAction("Result", new { userChoice = model.UsersGuess });
        }

        public ActionResult Result(string userChoice)
        {
            var model = new Game { UsersGuess = userChoice };

            model.Play();
            return View(model);
        }
    }
}

RockPaperScissors/RockPaperScissors/Views/Game/Play.cshtml
@model RockPaperScissors.Models.Game

<div class="jumbotron">
    <h1>Rock, Paper Scissors</h1>
    @using (Html.BeginForm())
    {
        <div>@Html.DisplayNameFor(m => m.UsersGuess)</div>
        foreach (string option in Model.Options)
        {

            <label>
                @Html.RadioButtonFor(m => m.UsersGuess, option, new { @class = "" })
                <span>@option</span>
            </label>
            <br />
        }
        @Html.ValidationMessageFor(m => m.UsersGuess)
        <input class="btn btn-primary btn-lg" type="submit" value="Play" />
    }
</div>

RockPaperScissors/RockPaperScissors/Views/Game/Result.cshtml
@model RockPaperScissors.Models.Game

<div class="jumbotron">
    <div>
        <h1>Results:</h1>
        <h2>Winner:</h2>
        <h4>@Model.Winner</h4>

        <div>
            @Html.ActionLink("Play again", "Play", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    </div>
</div>

RockPaperScissors/RockPaperScissors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Chase's Projects", "Play", "Game", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Play", "Game")</li>
                    @* Display Text, Method in Controller, Class *@
                    <li>@Html.ActionLink("Games", "Play", "Game")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>